version: '3'
services:
  # PHP Web Application
  web:
    container_name: guestbook-web
    build: ./web
    environment:
      DB_HOST: guestbook-db
      DB_NAME: guestbook
      DB_USER: guestbook
      DB_PASSWORD: guestbook
    ports:
    - "30201:80"
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: guestbook-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestbook
      MYSQL_USER: guestbook
      MYSQL_PASSWORD: guestbook
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  dbadmin:
    container_name: guestbook-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=guestbook-db
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 30202:80
    depends_on:
      - db
