apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    releases:
      - name: phpmyadmin
        repo: https://charts.bitnami.com/bitnami 
        remoteChart: phpmyadmin
        valuesFiles:
          - values.yaml
