apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    releases:
      - name: phpmyadmin-release
        repo: https://charts.bitnami.com/bitnami 
        remoteChart: phpmyadmin
        version: 10.3.5
        namespace: php-guestbook
        valuesFiles:
          - values.yaml
