auth:
  rootPassword: hogehoge
  database: guestbook
  username: guestbook
  password: guestbook
initdbScripts:
  initdb.sql: |-
    /* drop table */
    DROP TABLE IF EXISTS `guestbook`.`guest`;

    /* create table */
    CREATE TABLE `guestbook`.`guest` (
      `id` INT(32) NOT NULL AUTO_INCREMENT , 
      `name` VARCHAR(64) NOT NULL , 
      `email` VARCHAR(128) NOT NULL , 
      `address` VARCHAR(256) NOT NULL , 
      `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
      `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

    USE guestbook;

    SET CHARACTER_SET_CLIENT = utf8;
    SET CHARACTER_SET_CONNECTION = utf8;

    /* Insert Sample Guest Data */
    INSERT INTO `guest` (`name`, `email`, `address`) VALUES ('山田花子', 'yamada@example.com', '東京都港区六本木');
    INSERT INTO `guest` (`name`, `email`, `address`) VALUES ('田中一郎', 'tanaka@example.com', '東京都品川区高輪');
