apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: php-guestbook-web
    sync:
      infer:
        - '**/*'
profiles:
- name: localhost
  deploy:
    kubectl:
      manifests:
      - kubernetes/localhost/*
- name: envy
  deploy:
    kubectl:
      manifests:
      - kubernetes/envy/*
